### PR TITLE
Created new S2I template and updated README for ticket-monster demo

### PR DESCRIPTION
**Pull request by sabre1041**
Created template for building prepackaged applications using S2I build strategy

### CODE REVIEW

**Comment by etsauer** [comment]
@sabre1041 Awesome that you got this to work. Can you add something that explains the conceptual different between the two?

Do you see the S2I example replacing the custom builder now or in the near future? Sound like they can do the same thing as far as pulling an artifact from a repository.

**Comment by sabre1041** [comment]
@etsauer README has a general overview but ill add some "color" to signify the differences

Yes. The custom builder was previously required to overcome to lack of ability to inject environment variables into the S2I process during the beta. To simplify the repository structure, I configured the S2I script in the builder repo until we decide we can deprecate the custom builder and create a new repository in a final resting spot.

**Comment by etsauer** [comment]
@sabre1041 ok, should the readme perhaps indicate that the custom builder option is being deprecated and to use the s2i script?

**Comment by sabre1041** [comment]
Updated README with suggestions. @etsauer please review

**Pull request merged**
