### PR TITLE
Created OpenStack client docker container

### PR DESCRIPTION
**Pull request by sabre1041**
Created an OpenStack Docker client option for those who choose not to install the OpenStack clients or are unable to run the provisioning scripts

### CODE REVIEW

**Comment by etsauer** [comment]
This looks awesome. I'll test this when I get around to it. We may just want to standardize on something like this, instead of actually making everyone install client configs

**Comment by etsauer** [comment]
@sabre1041 can we get some testing instructions here?

**Comment by sabre1041** [comment]
Testing instructions:
1. Pull down code and navigate to _provisioning/openstack-docker-client_ folder
2. Run `run.sh` script which will build image and start container and provide a prompt for user interaction. See README for configuration switches if applicable (OpenStack configuration files, SSH keys)
3. Try to run `nova image-list` to view available images in OpenStack
4. Using boot2docker, I had issues resolving DNS address from the Red Hat VPN. I had to run `echo "10.3.0.3      control.os1.phx2.redhat.com" >> /etc/hosts` to make OpenStack resolve

**Comment by etsauer** [comment]
``` bash
$ ./run.sh 
time="2015-09-01T11:22:05-04:00" level=fatal msg="Get http:///var/run/docker.sock/v1.18/images/json: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?" 
Building Docker Image rhtconsulting/rhc-openstack-client....
Sending build context to Docker daemon 
FATA[0000] Post http:///var/run/docker.sock/v1.18/build?cgroupparent=&cpusetcpus=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=rhtconsulting%2Frhc-openstack-client: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 
Starting OpenStack Client Container....

FATA[0000] Post http:///var/run/docker.sock/v1.18/containers/create: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 
```

**Comment by sabre1041** [comment]
@etsauer is docker installed on your machine and configured? (should be prereqs...?)

**Comment by etsauer** [comment]
@sabre1041 yes, it is.

**Comment by etsauer** [comment]
``` bash
$ sudo ./run.sh --configdir=/home/esauer/.openstack/
Building Docker Image rhtconsulting/rhc-openstack-client....
...
/root/start.sh: line 14: /root/.openstack/*.sh: No such file or directory
cp: cannot stat '/root/ssh/id_rsa': No such file or directory
chmod: cannot access '/root/.ssh/id_rsa': No such file or directory
/root/start.sh: line 29: /root/.openstack/*.sh: No such file or directory
```

**Comment by sabre1041** [comment]
@etsauer ill add additional checks to avoid such errors

Issue may be due to having to run as sudo to execute script so it is unable to leverage the logged in users' profile. can you add the --configdir to point to the location containing your config file just to validate existing functionality

**Comment by sabre1041** [comment]
@esauer how did you execute the script? Did you sudo the entire script or only the docker commands

**Comment by etsauer** [comment]
@sabre1041 see above..  sudo'd the whole script.

**Comment by etsauer** [comment]
@sabre1041 also, per the above sample run, I already passed the --configdir option

**Comment by sabre1041** [comment]
@etsauer found solution to access denied error without requiring privileged container. Would you be able to retest?

**Comment by etsauer** [comment]
@sabre1041 retested, and it still works. I'm looking at a way that people don't have to sudo to run the script. I've found this post: http://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo.. trying to get that to work.

Any other ideas?

**Comment by sabre1041** [comment]
@etsauer this is good architectural discussion that we should bring up to the team. I go down the sudo pattern on the cicd server itself since Jenkins runs as a non privileged user. I added the Jenkins user to the sudoers file, but if we decide that a group modification makes the most sense, we can make the change for both approaches

**Comment by etsauer** [comment]
@sabre1041 ok, i got it to work. Here's some simple setup instructions to add to the readme.

```
sudo yum install -y docker
groupadd docker
usermod -a -G docker ${USER}
systemctl enable docker
systemctl start docker
reboot
```

**Comment by sabre1041** [comment]
@esauer is this a pattern that we should also pass down to the cicd server for the jenkins user?

**Comment by etsauer** [comment]
@sabre1041 yeah, it seems to be. I would keep it consistent.

**Comment by sabre1041** [comment]
@etsauer added troubleshooting documentation. please take a look when you get a chance

**Comment by etsauer** [comment]
I think this is a more appropriate error message to show for #2:

```
$ ./run.sh 
time="2015-09-01T11:32:36-04:00" level=fatal msg="Get http:///var/run/docker.sock/v1.18/images/json: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?" 
Building Docker Image rhtconsulting/rhc-openstack-client....
Sending build context to Docker daemon 
FATA[0000] Post http:///var/run/docker.sock/v1.18/build?cgroupparent=&cpusetcpus=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=rhtconsulting%2Frhc-openstack-client: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS? 
Starting OpenStack Client Container....

FATA[0000] Post http:///var/run/docker.sock/v1.18/containers/create: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS? 
```

Also, Issue #1 is misformatted.

**Comment by sabre1041** [comment]
@etsauer probably spent a good 5 mins trying to figure out what was wrong with the formatting in issue 1 without realizing it was the formatting of the title "issue 1"

Updated formatting and added more appropriate message to second issue in troubleshooting section

**Comment by etsauer** [comment]
@sabre1041 looks good.

**Pull request merged**
