### PR TITLE
Updates to CICD install script. Added new plugins, extended Docker support and fixes

### PR DESCRIPTION
**Pull request by sabre1041**
- Sudoers access to Jenkins user
- Update Jenkins plugins
- Nexus configurations
- General CICD Install polishing

### CODE REVIEW

**Comment by etsauer** [comment]
@sabre1041 I'm thinking we could actually tie this into provisioning via osc-provision. basically add a flag that kicks off a jenkins provision instead of an openshift provision. thoughts?

**Comment by sabre1041** [comment]
@etsauer since the cicd server is not necessarily tied to an ose installation, I am leaning toward keeping it separate. @obedin thoughts?

**Comment by etsauer** [comment]
@sabre1041 I'm not suggesting we spin up a cicd server with every new environment. I'm saying we could create an option in osc-provision to request a cicd instance OR an openshift env, and make use of the same provisioning scripts for both.

**Comment by sabre1041** [comment]
@esauer if we can still continue to leverage the cicd script as a standalone script but provide the ability to hook into it via the osc-provision script, i'm all for it

**Comment by etsauer** [comment]
@sabre1041 going to go ahead an merge. We can talk about integrating with full provisioning later.

**Pull request merged**
