### PR TITLE
New image build

### PR DESCRIPTION
**Pull request by oybed**
@etsauer KVM based image creation tool to prepare an image to be used with OpenStack.

To test: Make sure you're running on a system with libvirt/virt-manager installed and operational, then run: 
>> bash provisioning/kvm/create_base_img.sh -i=<path_to_RHEL7_iso>

### CODE REVIEW

**Comment by etsauer** [comment]
@oybed did you miss something in your testing line? '... -i=?'

**Comment by oybed** [comment]
@etsauer no, it's all there, just that I forgot to escape the < > characters - it's fixed now. Also, there's more of the same information in the comments block of the script, so I'd suggest reading those as well.

**Comment by etsauer** [comment]
@oybed just from the back and forth we've had trying to get this to run, I think we'll want to have a README in the kvm dir outlining what client packages are needed to run this (libvirt, glance, etc)

**Comment by oybed** [comment]
@etsauer yes, I'll create a README file (basically just extract the header from the script + enhance the write-up a bit)

**Comment by etsauer** [comment]
@oybed got this all to work. Once there's a README, i'll merge.

**Comment by oybed** [comment]
@etsauer please review the README file

**Comment by etsauer** [comment]
looks good, merging

**Pull request merged**
