### PR TITLE
Ability to Delete Environments

### PR DESCRIPTION
**Pull request by etsauer**
@oybed

### CODE REVIEW

**Comment by oybed** [comment]
@etsauer looked over the code, and the changes appears to be OK, but can you please provide steps for testing?

**Comment by etsauer** [comment]
@oybed 

Steps to test:
1. Create an Environment

``` bash
$ ./ose-utils/provisioning/osc-provision --num-nodes=2 --key=<key name> --no-install
...
Environment ID: <ENV_ID>
```
1. Verify that instances exist
2. Delete Environment

``` bash
$ ./ose-utils/provisioning/osc-provision --delete=<ENV_ID>
```
1. Verify instances and volumes are deleted

**Comment by oybed** [comment]
@etsauer 
The "Environment ID" is printed in the middle of other output, so a bit hard to see - but not a deal-breaker (maybe a future PR ?)

```
ose-utils/provisioning/osc-provision --num-nodes=2 --key=obedin-ose3-pub-key --no-install
Provisioning master. This could take several minutes.
Complete!
Provisioning 2 nodes. This could take several minutes.
Complete!
No keypair found. Creating one... Done
Pushing key for node 10.3.8.245...
Done
Pushing key for node 10.3.9.3...
Done
Pushing key for node 10.3.9.2...
Done
Skipping Installation Step. You'll need to do this manually.
Environment ID: FJqA0O5U
Master:
  - Hostname: 
  - IPs: 172.16.166.94|10.3.8.245
Nodes: 
- Node
-- Hostname: 
-- IPs: 172.16.166.94|10.3.8.245
- Node
-- Hostname: 
-- IPs: 172.16.166.96|10.3.9.3
- Node
-- Hostname: 
-- IPs: 172.16.166.93|10.3.9.2
DNS Server: 
```

**Comment by oybed** [comment]
@etsauer It indicates that the delete failed, but it actually worked - the log file shows nothing:

```
>> ose-utils/provisioning/osc-provision --delete=FJqA0O5U
ERROR: Delete failed. See log at ~/openstack_provision.log.
>> tail -n 5 ~/openstack_provision.log 
Tue Sep  1 23:23:52 MDT 2015: info: Adding a Volume
Tue Sep  1 23:23:55 MDT 2015: debug: Ran command at 0: [ $( nova volume-show 413c2533-f1c7-4c7a-bce5-aa9a421a4989 | grep -cE "status.*available" ) -eq 1 ]
Tue Sep  1 23:24:00 MDT 2015: info: Instance node-FJqA0O5U-21ddf17d-b15b-4b9d-99ff-fd345104d275 is accessible and ready to use.
Tue Sep  1 23:28:27 MDT 2015: info: Deleted servers: ecbda61c-23d1-4453-a81c-457c49c36a79 0ebd48cc-f0d1-4edc-95a3-f2a46c23c890 21ddf17d-b15b-4b9d-99ff-fd345104d275
Tue Sep  1 23:28:40 MDT 2015: info: Deleted volumes:  0cb70c3e-8a0b-4735-9066-de6a31412d95 7b897a7d-fb99-4ed8-a977-4d5253614771 413c2533-f1c7-4c7a-bce5-aa9a421a4989
```

**Comment by oybed** [comment]
@etsauer also, getting the following error when trying to do a complete install:

```
>> ose-utils/provisioning/osc-provision --num-nodes=3 --key=obedin-ose3-pub-key
Provisioning master. This could take several minutes.
Complete!
Provisioning 3 nodes. This could take several minutes.
Complete!
No keypair found. Creating one... Done
Pushing key for node 10.3.8.245...Done
Pushing key for node 10.3.9.3...Done
Pushing key for node 10.3.9.2...Done
Pushing key for node 10.3.9.20...Done
Beginning action: Prep
Loaded plugins: product-id, subscription-manager
Cleaning repos: rhel-7-server-eus-thirdparty-oracle-java-rpms
              : rhel-7-server-extras-rpms rhel-7-server-optional-rpms
              : rhel-7-server-ose-3.0-rpms rhel-7-server-rpms
Cleaning up everything
Loaded plugins: product-id, subscription-manager
Cleaning repos: rhel-7-server-eus-thirdparty-oracle-java-rpms
              : rhel-7-server-extras-rpms rhel-7-server-optional-rpms
              : rhel-7-server-ose-3.0-rpms rhel-7-server-rpms
Cleaning up everything
Loaded plugins: product-id, subscription-manager
No packages marked for update
Beginning action: DNS
Invalid Option: 172.16.166.96|10.3.9.3,172.16.166.94|10.3.9.2,172.16.166.97|10.3.9.20
ERROR: DNS Install & Configuration failed.
Environment ID: bgiMDv5i
Master:
  - Hostname: 
  - IPs: 172.16.166.93|10.3.8.245
Nodes: 
- Node
-- Hostname: 
-- IPs: 172.16.166.93|10.3.8.245
- Node
-- Hostname: 
-- IPs: 172.16.166.96|10.3.9.3
- Node
-- Hostname: 
-- IPs: 172.16.166.94|10.3.9.2
- Node
-- Hostname: 
-- IPs: 172.16.166.97|10.3.9.20
DNS Server: 
```

**Comment by etsauer** [comment]
@oybed I will move the ENV ID to the bottom of the output.

The DNS Failure is something that has been happening intermittently for a while. Not related to this PR.

**Comment by etsauer** [comment]
@oybed see changes

**Pull request merged**
