### PR TITLE
Added HTTPD reverse proxy

### PR DESCRIPTION
**Pull request by sabre1041**
Created a frontend reverse proxy for Jenkins and Nexus

New URLs:

```
Jenkins: http://<host>/jenkins
Nexus: http://<host>/nexus
```

I am continuing to expose the backend services for now so they can still be reached by existing applications for the time being

### CODE REVIEW

**Comment by etsauer** [comment]
@sabre1041 how do I test this?

**Comment by sabre1041** [comment]
@etsauer There is no automated provision of cloud instances. You can use the following instructions:
1. Create new instance in OpenStack. (small with ose-base and CICD security group)
2. Create 10GB volume and attach to instance at /dev/vdb
3. Pull code code and `run provisioning/cicd-install`

Verification:
Jenkins will be available at `http://<server>/jenkins`
Nexus will be available at `http://<server>/nexus`

**Comment by etsauer** [comment]
@sabre1041 i would switch out the apache index page with links to /jenkins and /nexus

**Comment by sabre1041** [comment]
@etsauer added a default index file to provide links to Jenkins and Nexus services

**Comment by etsauer** [comment]
Ok, looks good.

**Pull request merged**
